const DOTS_SIZE = 5;

class DotsAndBoxesGame {
  constructor(size = DOTS_SIZE) { this.restart(size); }
  restart(size = this.size) { this.size = size; this.currentPlayer = 'blue'; this.horizontal = Array.from({ length: size }, () => Array(size - 1).fill(null)); this.vertical = Array.from({ length: size - 1 }, () => Array(size).fill(null)); this.boxes = Array.from({ length: size - 1 }, () => Array(size - 1).fill(null)); this.gameOver = false; this.winner = null; }
  validEdge(kind, row, col) { return (kind === 'h' && row >= 0 && row < this.size && col >= 0 && col < this.size - 1) || (kind === 'v' && row >= 0 && row < this.size - 1 && col >= 0 && col < this.size); }
  edge(kind, row, col) { return kind === 'h' ? this.horizontal[row][col] : this.vertical[row][col]; }
  closeBoxes(kind, row, col) { const candidates = kind === 'h' ? [[row - 1, col], [row, col]] : [[row, col - 1], [row, col]]; let closed = 0; candidates.forEach(([boxRow, boxCol]) => { if (boxRow < 0 || boxCol < 0 || boxRow >= this.size - 1 || boxCol >= this.size - 1 || this.boxes[boxRow][boxCol]) return; if (this.horizontal[boxRow][boxCol] && this.horizontal[boxRow + 1][boxCol] && this.vertical[boxRow][boxCol] && this.vertical[boxRow][boxCol + 1]) { this.boxes[boxRow][boxCol] = this.currentPlayer; closed++; } }); return closed; }
  play(kind, row, col) { if (this.gameOver || !this.validEdge(kind, row, col) || this.edge(kind, row, col)) return false; if (kind === 'h') this.horizontal[row][col] = this.currentPlayer; else this.vertical[row][col] = this.currentPlayer; const closed = this.closeBoxes(kind, row, col); if (!closed) this.currentPlayer = this.currentPlayer === 'blue' ? 'red' : 'blue'; if (this.boxes.flat().every(Boolean)) { this.gameOver = true; const score = this.scores(); this.winner = score.blue === score.red ? 'draw' : score.blue > score.red ? 'blue' : 'red'; } return true; }
  scores() { return { blue: this.boxes.flat().filter(player => player === 'blue').length, red: this.boxes.flat().filter(player => player === 'red').length }; }
  serialize() { return JSON.stringify({ size:this.size, currentPlayer:this.currentPlayer, horizontal:this.horizontal, vertical:this.vertical, boxes:this.boxes, gameOver:this.gameOver, winner:this.winner }); }
  deserialize(value) { try { const state = JSON.parse(value), players = [null, 'blue', 'red']; const lines = (value, rows, cols) => Array.isArray(value) && value.length === rows && value.every(row => Array.isArray(row) && row.length === cols && row.every(player => players.includes(player))); if (!Number.isInteger(state.size) || state.size < 2 || !players.includes(state.currentPlayer) || !lines(state.horizontal, state.size, state.size - 1) || !lines(state.vertical, state.size - 1, state.size) || !lines(state.boxes, state.size - 1, state.size - 1)) return false; this.size=state.size; this.currentPlayer=state.currentPlayer; this.horizontal=state.horizontal; this.vertical=state.vertical; this.boxes=state.boxes; this.gameOver=Boolean(state.gameOver); this.winner=['blue','red','draw',null].includes(state.winner) ? state.winner : null; return true; } catch { return false; } }
}
if (typeof module !== 'undefined' && module.exports) module.exports = { DotsAndBoxesGame, DOTS_SIZE };
