import { Chess } from './vendor/chess-1.4.0.js';

const PIECES={wk:'♔',wq:'♕',wr:'♖',wb:'♗',wn:'♘',wp:'♙',bk:'♚',bq:'♛',br:'♜',bb:'♝',bn:'♞',bp:'♟'};
const FILES=['a','b','c','d','e','f','g','h'];

class ChessUI {
  constructor(){this.game=new Chess();this.selected=null;this.lastMove=null;this.flipped=false;this.thinking=false;this.engineReady=false;this.engine=null;this.playerColor='w';this.mode='computer';this.startMode='computer';this.hasSavedGame=this.load();this.bind();this.startEngine();this.render();if(this.hasSavedGame)this.maybeComputerMove();else this.showStart();}
  bind(){document.getElementById('new-game').addEventListener('click',()=>this.showStart());document.getElementById('flip').addEventListener('click',()=>{this.flipped=!this.flipped;this.save();this.render();});document.getElementById('level').addEventListener('change',()=>this.save());document.querySelectorAll('[data-color]').forEach(button=>button.addEventListener('click',()=>this.newGame(button.dataset.color)));document.querySelectorAll('[data-mode]').forEach(button=>button.addEventListener('click',()=>{this.startMode=button.dataset.mode;this.updateStartPanel();}));}
  showStart(){this.startMode=this.mode;document.getElementById('start-panel').hidden=false;this.updateStartPanel();}
  updateStartPanel(){const human=this.startMode==='human';document.getElementById('start-title').textContent=human?'Mensch gegen Mensch – Weiß beginnt.':'Welche Farbe spielst du?';document.getElementById('start-colors').innerHTML=human?'<button type="button" class="start-color" data-color="human">👥 Zu zweit starten</button>':'<button type="button" class="start-color" data-color="w">⚪ Weiß</button><button type="button" class="start-color black" data-color="b">⚫ Schwarz</button>';document.querySelectorAll('[data-mode]').forEach(button=>button.classList.toggle('active',button.dataset.mode===this.startMode));document.querySelectorAll('[data-color]').forEach(button=>button.addEventListener('click',()=>this.newGame(button.dataset.color)));}
  startEngine(){try{this.engine=new Worker('vendor/stockfish-18-lite-single.js');this.engine.onmessage=event=>this.onEngineLine(String(event.data));this.engine.onerror=()=>{this.engine=null;this.engineReady=false;if(this.thinking)this.randomMove();else this.render();};this.engine.postMessage('uci');this.engine.postMessage('isready');}catch(_){this.engine=null;}}
  onEngineLine(line){if(line==='readyok'){this.engineReady=true;if(this.thinking){this.thinking=false;this.computerMove();}else this.render();return;}if(!line.startsWith('bestmove '))return;const move=line.split(/\s+/)[1];if(!move||move==='(none)')return;this.thinking=false;try{this.lastMove={from:move.slice(0,2),to:move.slice(2,4)};this.game.move({from:move.slice(0,2),to:move.slice(2,4),promotion:move[4]||'q'});}catch(_){this.randomMove();}this.save();this.render();}
  newGame(color){this.mode=color==='human'?'human':this.startMode;this.playerColor=this.mode==='human'?'w':color==='b'?'b':'w';this.game=new Chess();this.selected=null;this.lastMove=null;this.thinking=false;this.flipped=this.playerColor==='b';document.getElementById('start-panel').hidden=true;this.save();this.render();this.maybeComputerMove();}
  save(){try{localStorage.setItem('chess-game',JSON.stringify({fen:this.game.fen(),lastMove:this.lastMove,level:document.getElementById('level').value,playerColor:this.playerColor,flipped:this.flipped,mode:this.mode}));}catch(_){}}
  load(){try{const data=JSON.parse(localStorage.getItem('chess-game'));if(!data?.fen)return false;this.game=new Chess(data.fen);this.lastMove=data.lastMove||null;this.playerColor=data.playerColor==='b'?'b':'w';this.mode=data.mode==='human'?'human':'computer';this.flipped=typeof data.flipped==='boolean'?data.flipped:this.playerColor==='b';setTimeout(()=>{document.getElementById('level').value=data.level||'5';},0);return true;}catch(_){try{localStorage.removeItem('chess-game');}catch(__){}return false;}}
  squareName(row,col){return `${FILES[col]}${8-row}`;}
  click(square){if(this.thinking||this.game.isGameOver()||(this.mode==='computer'&&this.game.turn()!==this.playerColor))return;if(this.selected){try{const move=this.game.move({from:this.selected,to:square,promotion:'q'});if(move){this.lastMove={from:move.from,to:move.to};this.selected=null;this.save();this.render();this.maybeComputerMove();return;}}catch(_){} }
    const piece=this.game.get(square);this.selected=piece?.color===this.game.turn()?square:null;this.render();}
  maybeComputerMove(){if(this.mode==='computer'&&this.game.turn()!==this.playerColor)this.computerMove();}
  computerMove(){if(this.game.isGameOver()||this.game.turn()===this.playerColor||this.thinking)return;this.thinking=true;this.render();const skill=document.getElementById('level').value;if(skill==='child'){setTimeout(()=>this.childMove(),450);return;}if(!this.engineReady){if(!this.engine)setTimeout(()=>this.randomMove(),250);return;}const time={0:150,5:300,10:650,16:1100}[skill]||300;this.engine.postMessage('stop');this.engine.postMessage('ucinewgame');this.engine.postMessage(`setoption name Skill Level value ${skill}`);this.engine.postMessage('setoption name UCI_LimitStrength value true');this.engine.postMessage(`position fen ${this.game.fen()}`);this.engine.postMessage(`go movetime ${time}`);}
  childMove(){if(this.game.turn()===this.playerColor){this.thinking=false;return;}const moves=this.game.moves({verbose:true});const safe=moves.filter(move=>{const next=new Chess(this.game.fen());next.move(move);return !next.moves({verbose:true}).some(reply=>reply.to===move.to&&(reply.flags.includes('c')||reply.flags.includes('e')));});const choices=safe.length?safe:moves;const move=choices[Math.floor(Math.random()*choices.length)];if(move){this.lastMove={from:move.from,to:move.to};this.game.move(move);}this.thinking=false;this.save();this.render();}
  randomMove(){if(this.game.turn()===this.playerColor)return;const moves=this.game.moves({verbose:true});if(moves.length){const move=moves[Math.floor(Math.random()*moves.length)];this.lastMove={from:move.from,to:move.to};this.game.move(move);}this.thinking=false;this.save();this.render();}
  status(){const playerName=this.playerColor==='w'?'Weiß':'Schwarz',computerName=this.playerColor==='w'?'Schwarz':'Weiß',turnName=this.game.turn()==='w'?'Weiß':'Schwarz';if(this.game.isCheckmate())return this.mode==='human'?`Schachmatt – ${this.game.turn()==='w'?'Schwarz':'Weiß'} gewinnt.`:this.game.turn()===this.playerColor?`Schachmatt – ${computerName} gewinnt.`:'Schachmatt – Du gewinnst!';if(this.game.isDraw())return 'Remis.';if(this.thinking)return this.engineReady?'Computer denkt …':'Computer wird geladen …';if(this.mode==='human')return this.game.isCheck()?`${turnName} ist im Schach.`:`${turnName} ist am Zug.`;return this.game.isCheck()?'Du bist im Schach.':`Du spielst ${playerName} – du bist am Zug.`;}
  render(){const board=document.getElementById('board');board.innerHTML='';document.getElementById('status').textContent=this.status();document.getElementById('level-control').hidden=this.mode==='human';document.getElementById('engine-note').hidden=this.mode==='human';const legalMoves=new Map();if(this.selected){for(const move of this.game.moves({square:this.selected,verbose:true})){legalMoves.set(move.to,move.flags.includes('c')||move.flags.includes('e'));}}const rows=this.flipped?[...Array(8).keys()]:[...Array(8).keys()].reverse();const cols=this.flipped?[...Array(8).keys()].reverse():[...Array(8).keys()];for(const rank of rows)for(const file of cols){const square=`${FILES[file]}${rank+1}`,piece=this.game.get(square),isLegal=legalMoves.has(square),button=document.createElement('button');button.type='button';button.className=`square ${(file+rank)%2?'':'dark'}${piece?.color==='b'?' black-piece':''}${this.selected===square?' selected':''}${isLegal?(legalMoves.get(square)?' legal-capture':' legal'):''}${this.lastMove&&(this.lastMove.from===square||this.lastMove.to===square)?' last':''}`;button.setAttribute('aria-label',`${square}${piece?` ${piece.color==='w'?'weiße':'schwarze'} ${piece.type}`:''}${isLegal?' mögliches Zielfeld':''}`);button.textContent=piece?PIECES[`${piece.color}${piece.type}`]:'';if(file===cols[0]){const rankLabel=document.createElement('span');rankLabel.className='coord';rankLabel.textContent=rank+1;button.append(rankLabel);}if(rank===rows[rows.length-1]){const fileLabel=document.createElement('span');fileLabel.className='file';fileLabel.textContent=FILES[file];button.append(fileLabel);}button.addEventListener('click',()=>this.click(square));board.append(button);}}
}
document.addEventListener('DOMContentLoaded',()=>window.chessGame=new ChessUI());
