const assert=require('assert'); const {BattleshipGame}=require('./schiffe.js');
const g=new BattleshipGame(); assert.strictEqual(g.canPlace('white',8,5,true),false); assert.ok(g.place('white',0,5,true)); assert.strictEqual(g.canPlace('white',10,4,true),false); assert.ok(g.place('white',20,4,true)); assert.ok(g.place('white',40,3,true)); assert.ok(g.place('white',60,3,true)); assert.ok(g.place('white',80,2,true)); assert.strictEqual(g.finishSetup(),'black'); assert.strictEqual(g.handoff,true); g.handoff=false; [0,20,40,60,80].forEach((i,n)=>assert.ok(g.place('black',i,BattleshipGame.fleet[n],true))); assert.strictEqual(g.finishSetup(),'battle'); assert.strictEqual(g.handoff,true); g.handoff=false; const hit=g.shoot(0);assert.strictEqual(hit.hit,true);assert.strictEqual(g.currentPlayer,'black');assert.strictEqual(g.handoff,true);const saved=g.serialize();const recovered=new BattleshipGame();assert.ok(recovered.deserialize(saved));assert.strictEqual(recovered.phase,'battle');console.log('Battleship tests passed');
const randomized=new BattleshipGame(); assert.ok(randomized.randomPlaceRemaining('white',()=>0)); assert.strictEqual(randomized.placed.white.length,5); assert.strictEqual(randomized.boards.white.filter(Boolean).length,17); assert.strictEqual(randomized.randomPlaceRemaining('black'),false); console.log('Battleship random placement tests passed');
const rerolled=new BattleshipGame(); assert.ok(rerolled.place('white',0,5,true)); assert.ok(rerolled.randomPlaceFleet('white',()=>0.99)); assert.strictEqual(rerolled.placed.white.length,5); assert.strictEqual(rerolled.boards.white.filter(Boolean).length,17); assert.strictEqual(rerolled.boards.white[0],0); console.log('Battleship reroll tests passed');
const computer=new BattleshipGame(); computer.restart('computer','hard'); assert.ok(computer.randomPlaceRemaining('white',()=>0)); assert.strictEqual(computer.finishSetup(),'battle'); assert.strictEqual(computer.placed.black.length,5); assert.strictEqual(computer.currentPlayer,'white'); assert.strictEqual(computer.handoff,false); assert.ok(computer.shoot(computer.availableShots('white')[0])); const computerShot=computer.aiPickShot(()=>0); assert.ok(Number.isInteger(computerShot)); assert.strictEqual(computer.shots.black[computerShot],0); assert.ok(computer.shoot(computerShot)); assert.ok(computer.currentPlayer==='white'||computer.phase==='finished'); console.log('Battleship computer tests passed');
const hunter=new BattleshipGame(); hunter.restart('computer','hard');
// Two separate ships have been hit. Hard must finish one of those hunts, not
// fall back to a global heatmap square somewhere else on the board.
hunter.boards.white[44]=1; hunter.boards.white[45]=1; hunter.boards.white[46]=1;
hunter.boards.white[18]=2; hunter.boards.white[28]=2; hunter.placed.white=[[44,45,46],[18,28]];
hunter.shots.black[45]=2; hunter.shots.black[18]=2;
const huntShot=hunter.aiPickShot(()=>0);
assert.ok([35,55,44,46,8,17,19,28].includes(huntShot), `hard AI must fire next to an active hit, got ${huntShot}`);
console.log('Battleship hard hunt tests passed');
